### PR TITLE
Mutable properties

### PR DESCRIPTION
**Pull request by chrislambe**
I had a need to modify state styles after plugin creation time, so I added some logic to expose those styles. It's not comprehensive, but I think it's a good start. Happy to answer any questions!

### CODE REVIEW

**Comment by dfstewart3** [comment]
Hi,
Can you please give a quick code example of how to use your changes. 
Thanks!

**Comment by chrislambe** [comment]
Of course! I ended up using this plugin to serve a proxy for a collection of checkboxes, each representing a state. In order to reflect a selected state, I had to change the stateSpecificStyles property after initialization. See below for a cropped example:
screen shot 2013-05-22 at 5 04 27 pm

Below is the relevant code, somewhat borrowed from the actual application. This has been truncated and converted from CoffeeScript, so please forgive any mistakes:
**Markup**

``` html
<div id="state-selection-map"></div>
<input type="checkbox" class="state" value="al">
<input type="checkbox" class="state" value="ak">
<input type="checkbox" class="state" value="az">
<input type="checkbox" class="state" value="ar">
<!-- snipped the other 46 states :) -->
```

**JavaScript**

``` javascript
$('#state-selection-map').usmap({/* snipped configuration details */});

// Change the state color when the checkbox changes
$('input.state').change(function(e) {
  // Get a reference to the checkbox as a jQuery object
  var $this = $(this);

  // Get the US Map plugin state ID
  var usMapStateId = $this.data('state-id').toUpperCase();

  // If the checkbox is checked, set the new color to blue, otherwise white
  var newFill = $this.is(':checked') ? '#0548d3' : '#fff';

  // Initialize and fill out style object
  var styles = {};
  styles[usMapStateId] = {fill:newFill};

  // Use new method to set the stateSpecificStyles property
  $('#state-selection-map').usmap('stateSpecificStyles',styles);
});
```

**Edit:** I switched from using the checkbox id attribute for state ID storage to the value attribute since if you use ID you can only have one checkbox for a given state. Value also better reflects real-world usage.

**Comment by dfstewart3** [comment]
Thank you so much!

Donna Stewart
[cid:image003.png@01CE57A2.6FAFE540]Green Mountain Consulting
7240 Goodlett Farms Pkwy
Memphis, TN 38016
901-507-9336
dstewart@gmcps.com

**Comment by mvgr2001** [comment]
on the load of the US Map I am trying to call my DB and change few state colors dependinig the DB Resource. But not able to change state colors dynamically on load. any help will be appreciated,.

**Comment by bbinkovitz** [comment]
This was a lifesaver, thank you so much. I hope the maintainers merge this.

**Comment by OdeToSpot** [comment]
Ahaha! This was just what I was looking for! Thanks for posting this.

**Comment by chrislambe** [comment]
Cleaning house. Guess this isn't getting merged!

**Pull request closed without merging**
